version: '3.8'
services:
  back:
    container_name: web-backend
    build: ./backend/
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 9900:8000
    env_file: ./.env
    volumes:
      - ./backend:/usr/src/app
      - ./frontend:/usr/src/app/frontend
