# Generated by Django 3.2.15 on 2023-01-26 16:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0002_rename_phone_order_phonenumber'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('price', django.db.models.manager.Manager()),
            ],
        ),
    ]
