# Generated by Django 3.2.15 on 2023-01-31 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0009_alter_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Необработан', max_length=50),
        ),
    ]
