# Generated by Django 3.2.15 on 2023-04-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0019_auto_20230215_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='amount',
            new_name='quantity',
        ),
    ]
