# Generated by Django 3.2.15 on 2023-01-27 11:24

from django.db import migrations


def fill_product_price(apps, schema_editor):
    Cart = apps.get_model('foodcartapp', 'Cart')
    cart_items = Cart.objects.all()
    for item in cart_items.iterator():
        item.price=item.product.price
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0006_cart_price'),
    ]

    operations = [
            migrations.RunPython(fill_product_price)
    ]
