# Generated by Django 3.2.15 on 2023-02-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0010_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'принят'), ('packing', 'упаковка'), ('delivery', 'доставка'), ('done', 'выполнен')], db_index=True, default='принят', max_length=50, verbose_name='Статус'),
        ),
    ]
