# Generated by Django 3.2.15 on 2023-02-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Обрабатывается'), ('packing', 'Упаковывается'), ('delivery', 'Передан в доставку'), ('done', 'Выполнен')], db_index=True, default='Обрабатывается', max_length=50, verbose_name='Статус'),
        ),
    ]
