# Generated by Django 3.2.15 on 2023-02-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0015_auto_20230201_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('clarify', 'Уточнить'), ('cash', 'Наличными'), ('card', 'Картой')], db_index=True, default='Уточнить', max_length=100, verbose_name='Способ оплаты'),
        ),
    ]
